-- MySQL Script generated by MySQL Workbench
-- Tue Apr 15 21:25:10 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema socialplus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema socialplus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `socialplus` DEFAULT CHARACTER SET utf8 ;
USE `socialplus` ;

-- -----------------------------------------------------
-- Table `socialplus`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `socialplus`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID uživatele',
  `username` VARCHAR(45) NOT NULL COMMENT 'Přihlašovací uživatelské jméno',
  `password` VARCHAR(45) NOT NULL COMMENT 'Přihlašovací heslo',
  `displayname` VARCHAR(45) NOT NULL COMMENT 'Zobrazované jméno',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `socialplus`.`networks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `socialplus`.`networks` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID sociální sítě',
  `owner_id` INT NOT NULL COMMENT 'ID majitele sociální sítě',
  `network_type` VARCHAR(45) NOT NULL COMMENT 'Typ sociální sítě (např. Facebook, Twitter)',
  `network_name` VARCHAR(45) NOT NULL COMMENT 'Název sociální sítě',
  `note` VARCHAR(45) NULL COMMENT 'Poznámka autora',
  PRIMARY KEY (`id`, `owner_id`),
  INDEX `fk_networks_users1_idx` (`owner_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_networks_users1`
    FOREIGN KEY (`owner_id`)
    REFERENCES `socialplus`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `socialplus`.`network_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `socialplus`.`network_tokens` (
  `network_id` INT NOT NULL COMMENT 'ID sociální sítě',
  `token_name` VARCHAR(45) NOT NULL COMMENT 'Název tokenu',
  `token` VARCHAR(45) NOT NULL COMMENT 'Token',
  PRIMARY KEY (`network_id`, `token_name`),
  INDEX `network_tokens_networks1_idx` (`network_id` ASC),
  CONSTRAINT `fk_network_tokens_networks1`
    FOREIGN KEY (`network_id`)
    REFERENCES `socialplus`.`networks` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `socialplus`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `socialplus`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID příspěvku',
  `creator_id` INT NOT NULL COMMENT 'Tvůrce příspěvku',
  PRIMARY KEY (`id`),
  INDEX `fk_posts_users_idx` (`creator_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_posts_users`
    FOREIGN KEY (`creator_id`)
    REFERENCES `socialplus`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `socialplus`.`contents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `socialplus`.`contents` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID obsahu jednotlivých příspěvků',
  `posts_id` INT NOT NULL COMMENT 'ID postu, ke kterému obsah příspěvku patří',
  `content` MEDIUMTEXT NOT NULL COMMENT 'Obsah příspěvku',
  PRIMARY KEY (`id`),
  INDEX `fk_contents_posts1_idx` (`posts_id` ASC),
  CONSTRAINT `fk_contents_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `socialplus`.`posts` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `socialplus`.`posted_content`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `socialplus`.`posted_content` (
  `posts_id` INT NOT NULL COMMENT 'ID příspěvku',
  `networks_id` INT NOT NULL COMMENT 'ID networku, na kterou je příspěvek odesílán',
  `contents_id` INT NOT NULL COMMENT 'ID obsahu příspěvku, který je odeslán na danou síť',
  `post_date` DATETIME NULL COMMENT 'Datum, kdy má být příspěvek postnut',
  `actual_post_date` DATETIME NULL COMMENT 'Skutečné datum odeslání příspěvku vzhledem k možným zpožděním API nebo případným problémům',
  `network_post_id` VARCHAR(45) NULL COMMENT 'ID příspěvku na sociální sítí',
  PRIMARY KEY (`posts_id`, `networks_id`),
  INDEX `fk_post_content_networks1_idx` (`networks_id` ASC),
  INDEX `fk_post_content_contents1_idx` (`contents_id` ASC),
  CONSTRAINT `fk_post_content_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `socialplus`.`posts` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_content_networks1`
    FOREIGN KEY (`networks_id`)
    REFERENCES `socialplus`.`networks` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_content_contents1`
    FOREIGN KEY (`contents_id`)
    REFERENCES `socialplus`.`contents` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
KEY_BLOCK_SIZE = 8;


-- -----------------------------------------------------
-- Table `socialplus`.`users_has_networks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `socialplus`.`users_has_networks` (
  `networks_id` INT NOT NULL COMMENT 'ID sociální sítě, ke které je udělován přístup',
  `granter_id` INT NOT NULL COMMENT 'ID uživatele, který oprávnění přiděluje',
  `grantee_id` INT NOT NULL COMMENT 'ID uživatele, kterému je přidělováno oprávnění',
  `permission` VARCHAR(45) NOT NULL COMMENT 'Typ oprávnění',
  PRIMARY KEY (`networks_id`, `granter_id`, `grantee_id`),
  INDEX `fk_users_has_networks_networks2_idx` (`networks_id` ASC, `granter_id` ASC),
  INDEX `fk_users_has_networks_users2_idx` (`grantee_id` ASC),
  CONSTRAINT `fk_users_has_networks_users2`
    FOREIGN KEY (`grantee_id`)
    REFERENCES `socialplus`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_networks_networks2`
    FOREIGN KEY (`networks_id` , `granter_id`)
    REFERENCES `socialplus`.`networks` (`id` , `owner_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `socialplus`.`attachments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `socialplus`.`attachments` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID attachmentu',
  `posts_id` INT NOT NULL COMMENT 'ID příspěvku, kterému attachment patří',
  `path` VARCHAR(45) NOT NULL COMMENT 'Cesta k souboru attachmentu',
  PRIMARY KEY (`id`, `posts_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_attachments_posts2_idx` (`posts_id` ASC),
  CONSTRAINT `fk_attachments_posts2`
    FOREIGN KEY (`posts_id`)
    REFERENCES `socialplus`.`posts` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `socialplus`.`posted_content_has_attachments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `socialplus`.`posted_content_has_attachments` (
  `posts_id` INT NOT NULL COMMENT 'ID vybraného postu, ke kterému attachment patří',
  `networks_id` INT NOT NULL COMMENT 'ID networku vybraného postu, ke kterému attachment patří',
  `attachments_id` INT NOT NULL COMMENT 'ID attachmentu, který patří k vybranému příspěvku dané sociální sítě',
  PRIMARY KEY (`posts_id`, `networks_id`, `attachments_id`),
  INDEX `fk_posted_content_has_attachments_attachments1_idx` (`attachments_id` ASC),
  INDEX `fk_posted_content_has_attachments_posted_content1_idx` (`posts_id` ASC, `networks_id` ASC),
  CONSTRAINT `fk_posted_content_has_attachments_posted_content1`
    FOREIGN KEY (`posts_id` , `networks_id`)
    REFERENCES `socialplus`.`posted_content` (`posts_id` , `networks_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posted_content_has_attachments_attachments1`
    FOREIGN KEY (`attachments_id`)
    REFERENCES `socialplus`.`attachments` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `socialplus`.`post_editors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `socialplus`.`post_editors` (
  `posts_id` INT NOT NULL COMMENT 'ID příspěvku ke kterému je přidělen přístup k editaci',
  `users_id` INT NOT NULL COMMENT 'Uživatel, kterému je přiděleno právo k editaci',
  PRIMARY KEY (`posts_id`, `users_id`),
  INDEX `fk_post_editors_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_post_editors_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `socialplus`.`posts` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_editors_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `socialplus`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
